jobs:
  openvidu_angular_e2e:
    name: OpenVidu Angular E2E tests
    needs: test_setup
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.commit_sha || github.sha }}
    - continue-on-error: true
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - continue-on-error: true
      uses: actions/download-artifact@v3
      with:
        name: openvidu-browser
        path: openvidu-components-angular
    - continue-on-error: true
      name: Run Browserless Chrome
      run: docker run -d -p 3000:3000 --network host browserless/chrome:1.57-chrome-stable
    - continue-on-error: true
      name: Run openvidu-server-kms
      run: 'docker run -p 4443:4443 --rm -d \

        -e OPENVIDU_SECRET=MY_SECRET \

        openvidu/openvidu-dev:latest

        '
    - continue-on-error: true
      name: Install openvidu-browser and dependencies
      run: 'cd openvidu-components-angular

        npm install openvidu-browser-*.tgz

        '
    - continue-on-error: true
      name: Build openvidu-angular
      run: npm run lib:build --prefix openvidu-components-angular
    - continue-on-error: true
      name: Build openvidu-angular-testapp
      run: npm run build --prefix openvidu-components-angular
    - continue-on-error: true
      name: Serve openvidu-angular-testapp
      run: npm run start-prod --prefix openvidu-components-angular &
    - continue-on-error: true
      name: Run openvidu-angular E2E
      run: npm run lib:e2e-ci --prefix openvidu-components-angular
  test_setup:
    name: Test setup
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.commit_sha || github.sha }}
    - continue-on-error: true
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - continue-on-error: true
      name: Commit URL
      run: echo https://github.com/OpenVidu/openvidu/commit/${{ inputs.commit_sha
        || github.sha }}
    - continue-on-error: true
      env:
        BRANCH_NAME: ${{ github.ref_name }}
        COMMIT_MESSAGE: ${{ github.event.head_commit.message || 'Manually' }}
        COMMIT_URL: ${{ github.event.commits[0].url || 'Manually' }}
        GITHUB_TOKEN: ${{ secrets.OPENVIDU_DISPATCH_EVENT_GA }}
      name: Send repository dispatch event
      run: 'curl \

        -X POST \

        -H "Accept: application/vnd.github+json" \

        -H "Authorization: Bearer ${GITHUB_TOKEN}" \

        https://api.github.com/repos/OpenVidu/openvidu-call/dispatches \

        -d ''{"event_type":"openvidu-components-angular","client_payload":{"commit-message":"''"$COMMIT_MESSAGE"''","commit-ref":"''"$COMMIT_URL"''",
        "branch-name":"''"$BRANCH_NAME"''"}}''

        '
    - continue-on-error: true
      name: Build openvidu-browser
      run: 'cd openvidu-browser

        npm install

        npm run build && \

        npm pack

        '
    - continue-on-error: true
      uses: actions/upload-artifact@v3
      with:
        name: openvidu-browser
        path: openvidu-browser/openvidu-browser-*.tgz
  webcomponent_e2e:
    name: Webcomponent E2E CE tests
    needs: test_setup
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.commit_sha || github.sha }}
    - continue-on-error: true
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - continue-on-error: true
      uses: actions/download-artifact@v3
      with:
        name: openvidu-browser
        path: openvidu-components-angular
    - continue-on-error: true
      name: Run Browserless Chrome
      run: docker run -d -p 3000:3000 --network host browserless/chrome:1.57-chrome-stable
    - continue-on-error: true
      name: Run openvidu-server-kms
      run: 'docker run -p 4443:4443 --rm -d \

        -e OPENVIDU_SECRET=MY_SECRET \

        openvidu/openvidu-dev:latest

        '
    - continue-on-error: true
      name: Install openvidu-browser and dependencies
      run: 'cd openvidu-components-angular

        npm install openvidu-browser-*.tgz

        '
    - continue-on-error: true
      name: Build openvidu-angular
      run: npm run lib:build --prefix openvidu-components-angular
    - continue-on-error: true
      name: Build openvidu-webcomponent
      run: npm run webcomponent:build --prefix openvidu-components-angular
    - continue-on-error: true
      name: Serve Webcomponent Testapp
      run: npm run webcomponent:serve-testapp --prefix openvidu-components-angular
        &
    - continue-on-error: true
      name: Run Webcomponent E2E
      run: npm run webcomponent:e2e-ci --prefix openvidu-components-angular
  webcomponent_e2e_pro:
    if: false
    name: Webcomponent E2E PRO tests
    needs: test_setup
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - continue-on-error: true
      uses: actions/download-artifact@v3
      with:
        name: openvidu-browser
        path: openvidu-components-angular
    - continue-on-error: true
      name: Run Browserless Chrome
      run: docker run -d -p 3000:3000 --network host browserless/chrome:1.57-chrome-stable
    - continue-on-error: true
      name: Install openvidu-browser and dependencies
      run: 'cd openvidu-components-angular

        npm install openvidu-browser-*.tgz

        '
    - continue-on-error: true
      name: Build openvidu-angular
      run: npm run lib:build --prefix openvidu-components-angular
    - continue-on-error: true
      name: Build openvidu-webcomponent
      run: npm run webcomponent:build --prefix openvidu-components-angular
    - continue-on-error: true
      name: Serve Webcomponent Testapp
      run: npm run webcomponent:serve-testapp --prefix openvidu-components-angular
        &
    - continue-on-error: true
      env:
        OPENVIDU_SECRET: ${{ secrets.OPENVIDU_CALL_NEXT_SECRET }}
        OPENVIDU_SERVER_URL: ${{ secrets.OPENVIDU_CALL_NEXT_URL }}
      name: Run Webcomponent E2E PRO
      run: npm run webcomponent:e2e-pro-ci --prefix openvidu-components-angular
name: openvidu-components-angular E2E
on:
  repository_dispatch:
    types: trigger-ga___openvidu-components-angular-E2E.yml
